# Generated by Django 3.2.25 on 2024-10-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_product_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='user_checkboxes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='user_update_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
