# Generated by Django 5.1.2 on 2024-10-16 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20241014_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtocart',
            name='cart_total_price',
        ),
        migrations.RemoveField(
            model_name='addtocart',
            name='cart_total_quantity',
        ),
    ]
